// Package swaggo Code generated by swaggo/swag. DO NOT EDIT
package swaggo

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Flighthours API Support",
            "url": "https://flighthours.com/support",
            "email": "support@flighthours.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/messages": {
            "get": {
                "description": "Obtiene una lista de mensajes del sistema con filtros opcionales. Permite filtrar por módulo, tipo, categoría y estado activo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Listar mensajes del sistema",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por módulo (ej: users, flights, bookings)",
                        "name": "module",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por tipo (ERROR, WARNING, INFO, SUCCESS)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por categoría (usuario_final, sistema, validacion)",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por estado activo (true, false)",
                        "name": "active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de mensajes obtenida exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageListResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo mensaje del sistema con tipo, categoría y contenido. Los mensajes se utilizan para mostrar información, advertencias y errores a los usuarios.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Crear un nuevo mensaje del sistema",
                "parameters": [
                    {
                        "description": "Datos del mensaje a crear",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Mensaje creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "El código del mensaje ya existe",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/reload": {
            "post": {
                "description": "Recarga el caché de mensajes desde la base de datos. Útil después de hacer cambios masivos a mensajes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Recargar caché de mensajes",
                "responses": {
                    "200": {
                        "description": "Caché recargado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.CacheReloadResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/{id}": {
            "get": {
                "description": "Obtiene los detalles de un mensaje del sistema específico por su ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Obtener un mensaje por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del mensaje (encoded)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mensaje encontrado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensaje no encontrado",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza un mensaje del sistema existente. Permite modificar tipo, categoría, contenido y estado activo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Actualizar un mensaje del sistema",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del mensaje (encoded)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del mensaje a actualizar",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mensaje actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageUpdatedResponse"
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensaje no encontrado",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina un mensaje del sistema de forma permanente. Esta acción no se puede deshacer.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Eliminar un mensaje del sistema",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del mensaje (encoded)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mensaje eliminado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageDeletedResponse"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Mensaje no encontrado",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Crea una nueva cuenta de empleado en el sistema con sincronización a Keycloak. Incluye validación de datos, verificación de duplicados y creación de usuario en el sistema de autenticación.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Registrar nueva cuenta de empleado",
                "parameters": [
                    {
                        "description": "Datos del empleado a registrar",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.EmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Cuenta creada exitosamente",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.RegisterEmployeeResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Error de validación - Datos inválidos o incompletos",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Conflicto - Email o número de identidad ya registrado",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "$ref": "#/definitions/middleware.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_champion19_flighthours-api_core_interactor_services_domain.MessageType": {
            "type": "string",
            "enum": [
                "ERROR",
                "EXITO",
                "WARNING",
                "INFO",
                "DEBUG"
            ],
            "x-enum-varnames": [
                "TypeError",
                "TypeSuccess",
                "TypeWarning",
                "TypeInfo",
                "TypeDebug"
            ]
        },
        "handlers.CacheReloadResponse": {
            "type": "object",
            "properties": {
                "after_count": {
                    "type": "integer"
                },
                "before_count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.EmployeeRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "airline": {
                    "type": "string"
                },
                "bp": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "identificationNumber": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "handlers.Link": {
            "type": "object",
            "properties": {
                "href": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "rel": {
                    "type": "string"
                }
            }
        },
        "handlers.MessageCreatedResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.Link"
                    }
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "handlers.MessageDeletedResponse": {
            "type": "object"
        },
        "handlers.MessageListResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.Link"
                    }
                },
                "count": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.MessageResponse"
                    }
                }
            }
        },
        "handlers.MessageRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "module": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_champion19_flighthours-api_core_interactor_services_domain.MessageType"
                }
            }
        },
        "handlers.MessageResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.Link"
                    }
                },
                "active": {
                    "type": "boolean"
                },
                "category": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "module": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/github_com_champion19_flighthours-api_core_interactor_services_domain.MessageType"
                }
            }
        },
        "handlers.MessageUpdatedResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.Link"
                    }
                }
            }
        },
        "handlers.RegisterEmployeeResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.Link"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "middleware.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Business message code",
                    "type": "string"
                },
                "data": {},
                "message": {
                    "description": "Business message content",
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "middleware.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/flighthours/api/v1",
	Schemes:          []string{},
	Title:            "Flighthours Backend API",
	Description:      "API RESTful para la plataforma Flighthours, implementada con arquitectura hexagonal y siguiendo los principios del Richardson Maturity Model (Nivel 2-3) con HATEOAS.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
